### ISSUE TITLE
Unexpected sorting from pipe

### ISSUE THREAD

**Issue by SamMade** [Bellese/angular-design-system#14]
we're seeing a weird ordering in our data with the pipe...  `sorting: false`.  

**actual result** 
array is getting sorted 

**expected result** 
no sorting done and object gives items the way it was imported...  

https://github.com/Bellese/angular-design-system/blob/132f0b147cc62bd90645b6a914a37839de15f66d/src/app/modules/pipes/sorting.pipe.ts#L11-L17

recommend adding :
```
    if (!event) return items;
```
right after the line 12

**Comment by JLLproduction** [comment]
Just resolved this, thanks for offering a solution and identifying this issue
