### ISSUE TITLE
ngx-charts downgrade to 7.4

### ISSUE THREAD

**Issue by SamMade** [Bellese/angular-design-system#22]
https://github.com/Bellese/angular-design-system/blob/2b7c3c7f76df7c16bc97b78351dcfd3d525cc8fe/package.json#L54

ngx-charts 8 which is declared as a dependency here is for angular 6.  Please declare 7.4 which is the proper version for angular 5

#23 should resolve

**Comment by JLLproduction** [comment]
We should upgrade to Angular 6 instead. We have to wait on this. I commented in the pull request
