### ISSUE TITLE
modal close focus 

### ISSUE THREAD

**Issue by SamMade** [Bellese/angular-design-system#30]
https://github.com/Bellese/angular-design-system/blob/85628de74c28a0faf3e3a29c40156c0d0311e0db/src/app/modules/table/table-data/table-data.component.html#L30

since we have gotten rid of the modal element from the table... the button should have the ability to have an `id` attribute so we can pass that along in the modal service for focus to return back to that element when the modal is closed.

or option 2 would be to accept an event target instead of the `id` in the modal service.

**Comment by JLLproduction** [comment]
Sam lets set up a call so I can better understand.

**Comment by JLLproduction** [comment]
I will allow for table button to have an id option passed. you will need to add that as a key value in your api
