### ISSUE TITLE
NPM Vulnerability Findings

### ISSUE THREAD

**Issue by joffutt4** [Bellese/angular-design-system#6]
When performing NPM install on this design system, NPM reported multiple security findings from dependencies. I believe some can be resolved by NPM, but a lot of them require manual updating to resolve the issues. @JLLproduction @aproberts01 can you guys take a look and make sure that we can get these findings resolved without breaking changes?

**Comment by JLLproduction** [comment]
This issue is related to VPN only. Discovery shows this to not be an issue in general, but on VPN all things even WIFI need verified certificates. However, some external libraries will have self signed certificates, and will through a security warning to our VPN.
